### ISSUE TITLE
Cannot compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by j75** [wd5gnr/qtl866#11]
Hello!

Trying to build the executable with QtCreator on a Ubuntu amd64 produces the following messages:

```
mainwindow.cpp: In function 'QString getColoredText(QString, QString)':
mainwindow.cpp:37:63: error: 'QStringLiteral' was not declared in this scope
     return QStringLiteral("<span style='color: %1;'>%2</span>").arg(
                                                               ^
mainwindow.cpp:40:22: error: 'class QString' has no member named 'toHtmlEscaped'
                     .toHtmlEscaped()
```

Any idea how to fix that?

**Comment by wd5gnr** [comment]
I am not able to reproduce this. What version of Qt are you building against?
